# Generated by Django 4.2.14 on 2024-12-10 21:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "presumed_profit_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "real_profit_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
