# Generated by Django 4.2.14 on 2025-03-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tax",
            name="presumed_profit_deducts_net_cost",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tax",
            name="real_profit_deducts_net_cost",
            field=models.BooleanField(default=False),
        ),
    ]
