# Generated by Django 4.2.14 on 2025-03-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("icms", "0002_alter_ncm_code_icmsrate_unique_state_group_icmsrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="ncm",
            name="percentage_end_consumer",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
