# Generated by Django 4.2.14 on 2025-03-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("margin", "0003_alter_percentage_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="is_end_consumer",
            field=models.BooleanField(default=False),
        ),
    ]
