# Generated by Django 4.2.14 on 2025-03-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("margin", "0004_contract_is_end_consumer"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="admin_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="end_consumer_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="icms_taxpayer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contract",
            name="taxes_considered",
            field=models.TextField(blank=True, null=True),
        ),
    ]
