# Generated by Django 4.2.14 on 2025-03-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("margin", "0005_contract_admin_rate_contract_end_consumer_rate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="icms_taxpayer",
            new_name="is_icms_taxpayer",
        ),
    ]
